development:
  adapter: postgresql
  encoding: unicode
  database: prosperity_dummy_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: prosperity_dummy_test
  pool: 5
  username: postgres
  password:

